const fs = require("fs");
const path = require("path");

const outDir = path.join(process.cwd(), "src", "lib");
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const image = fs.readFileSync(path.join("public", "postit.png")).toString("base64");
const image2 = fs.readFileSync(path.join("public", "postit2.png")).toString("base64");
const image3 = fs.readFileSync(path.join("public", "postit3.png")).toString("base64");
const font = fs.readFileSync(path.join("public", "font", "NanumJinJuBagGyeongACe.ttf")).toString("base64");

const content = `// auto-generated by scripts/encode-assets.js
export const POSTIT_1__BASE64 = "data:image/png;base64,${image}";
export const POSTIT_2__BASE64 = "data:image/png;base64,${image2}";
export const POSTIT_3__BASE64 = "data:image/png;base64,${image3}";
export const NANUM_FONT_BASE64 = "data:font/ttf;base64,${font}";
`;

fs.writeFileSync(path.join(outDir, "base64-assets.ts"), content, "utf8");
console.log("폰트와 이미지 base64 문자열 생성됨");
